# .goreleaser.yml
project_name: device-flow-proxy

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod download
    - git checkout -- go.sum

builds:
  # You can have multiple builds defined as a yaml list
  -
    # Binary name.
    # Can be a path (e.g. `bin/app`) to wrap the binary in a directory.
    # Default is the name of the project directory.
    binary: device-flow-proxy-bin

    # Custom environment variables to be set during the builds.
    # Default is empty.
    env:
      - CGO_ENABLED=0

    # Custom ldflags templates.
    # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser`.
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.FullCommit}} -X main.date={{.Date}} -x main.tag={{.Tag}}

    # GOOS list to build for.
    # For more info refer to: https://golang.org/doc/install/source#environment
    # Defaults are darwin and linux.
    goos:
      - linux
      - darwin

    # GOARCH to build for.
    # For more info refer to: https://golang.org/doc/install/source#environment
    # Defaults are 386, amd64 and arm64.
    goarch:
      - amd64
      - arm64

checksum:
  algorithm: sha256

release:

  # If set to auto, will mark the release as not ready for production
  # in case there is an indicator for this in the tag e.g. v1.0.0-rc1
  # If set to true, will mark the release as not ready for production.
  # Default is false.
  prerelease: auto

  # You can change the name of the release.
  # Default is `{{.Tag}}` on OSS and `{{.PrefixedTag}}` on Pro.
  name_template: "{{.Tag}}"

dockers:
  - image_templates: ["ghcr.io/wraix/{{.ProjectName}}:{{ .Version }}-linux-arm64"]
    use: buildx
    goarch: arm64
    dockerfile: .docker/Dockerfile.goreleaser
    build_flag_templates: ["--platform=linux/arm64/v8"]
    skip_push: auto

  - image_templates: ["ghcr.io/wraix/{{.ProjectName}}:{{ .Version }}-linux-amd64"]
    use: buildx
    goarch: amd64
    dockerfile: .docker/Dockerfile.goreleaser
    build_flag_templates: ["--platform=linux/amd64"]
    skip_push: auto

docker_manifests:
  - name_template: ghcr.io/wraix/{{.ProjectName}}:v{{ .Major }}
    image_templates:
      - ghcr.io/wraix/{{.ProjectName}}:{{ .Version }}-linux-arm64
      - ghcr.io/wraix/{{.ProjectName}}:{{ .Version }}-linux-amd64
    skip_push: auto
  - name_template: ghcr.io/wraix/{{.ProjectName}}:v{{ .Major }}.{{ .Minor }}
    image_templates:
      - ghcr.io/wraix/{{.ProjectName}}:{{ .Version }}-linux-arm64
      - ghcr.io/wraix/{{.ProjectName}}:{{ .Version }}-linux-amd64
    skip_push: auto
  - name_template: ghcr.io/wraix/{{.ProjectName}}:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}
    image_templates:
      - ghcr.io/wraix/{{.ProjectName}}:{{ .Version }}-linux-arm64
      - ghcr.io/wraix/{{.ProjectName}}:{{ .Version }}-linux-amd64
    skip_push: auto
  - name_template: ghcr.io/wraix/{{.ProjectName}}:latest
    image_templates:
      - ghcr.io/wraix/{{.ProjectName}}:{{ .Version }}-linux-arm64
      - ghcr.io/wraix/{{.ProjectName}}:{{ .Version }}-linux-amd64
    skip_push: auto
