# Dockerfile References: https://docs.docker.com/engine/reference/builder/

FROM golang:1.17-alpine

# Add Maintainer Info
LABEL maintainer="wraix"

RUN apk add --update --no-cache ca-certificates git curl

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy everything from the current directory to the PWD(Present Working Directory) inside the container
COPY . .

# Setup go mod
RUN go mod tidy

# Development requires fresh
RUN go get github.com/ivpusic/rerun
# Cache for rerun
RUN mkdir /.cache

# This container exposes port 443 to the docker network
EXPOSE 8080

ENTRYPOINT ["rerun"]
CMD ["-a", "serve"]
