name: CD

on:
  push:
    tags:
      - '*v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

env:
  REGISTRY: ghcr.io

jobs:
  goreleaser:
    name: Build, Test & Release
    strategy:
      matrix:
        go-version:
          - 1.17.x
        os:
          - ubuntu-18.04

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
